### ISSUE TITLE
Feedback: First Challenge Submission

### ISSUE THREAD

**Issue by anselb** [ryanlsmith4/cs-1.3-core-data#1]
- Nice use of `ord()` for getting the index of the character. I glad you explained it in a comment on line 52, but the comment on line 28 was a bit unclear (what is the target?).
- Overall, your comments seem to do a good job of what is happening. I would recommend trying to comment your string functions similarly to what you did for the number base functions or the search functions.
- Your use of find_index in contains seems good; however, I don't think you are getting that much benefit from calling find_index in your find_all_indexes, seeing that find_index and find_all_indexes share a lot of the same code. You might consider refactoring again and calling find_all_indexes in find_index as find_all_indexes seems to already to the job of find_indexes and more.

**Comment by ryanlsmith4** [comment]
Thanks for the feedback Ansel! I like your input!
